# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: https://github.com/jupyterlab/extension-template
author_name: Voila contributors
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: voila_topbar
mimetype: ''
mimetype_name: ''
project_short_description: A Voila extension
python_name: voila_topbar
repository: https://github.com/voila-dashboards/voila-topbar
test: false
viewer_name: ''
